// Real caption-only UI acceptance. Does not click any paid AI action.
const { chromium } = require('playwright')
const fs = require('node:fs/promises')
const path = require('node:path')
const assert = require('node:assert/strict')

;(async () => {
  const folder = path.resolve(__dirname, '../../.local/learning-real-probes')
  const results = JSON.parse(await fs.readFile(path.join(folder, 'api-results.json'), 'utf8'))
  const ready = results.find(item => item.platform === 'YouTube' && item.status === 'ready')
  assert.ok(ready, 'Real YouTube captions are required')
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
    await page.goto((process.env.LEARNING_TEST_URL || 'http://127.0.0.1:8181') + '/#learn/' + ready.id)
    await page.getByRole('heading', { name: ready.title, exact: true }).waitFor({ state: 'visible' })
    assert.match(await page.getByLabel('切换字幕语言').locator('option:checked').innerText(), /人工字幕/)
    assert.equal(await page.getByRole('button', { name: '生成总结', exact: true }).isDisabled(), true)
    await page.getByRole('button', { name: '字幕原文', exact: true }).click()
    await page.getByText('1–100 / 333 段', { exact: true }).waitFor({ state: 'visible' })
    assert.equal(await page.locator('.transcript-cue').count(), 100)
    await page.getByRole('button', { name: '下一页', exact: true }).click()
    await page.getByText('101–200 / 333 段', { exact: true }).waitFor({ state: 'visible' })
    await page.getByRole('button', { name: '上一页', exact: true }).click()
    await page.getByText('1–100 / 333 段', { exact: true }).waitFor({ state: 'visible' })
    await page.locator('.learning-layout').evaluate(element => element.scrollTo({ top: 0 }))
    await page.screenshot({ path: path.join(folder, 'real-youtube-transcript.png'), fullPage: true })
    await page.reload()
    await page.getByRole('heading', { name: ready.title, exact: true }).waitFor({ state: 'visible' })
    const bili = results.find(item => item.platform === 'Bilibili' && item.status === 'ready')
    assert.ok(bili, 'Real Bilibili captions are required')
    await page.locator('.history-select').filter({ hasText: bili.title }).click()
    await page.getByRole('heading', { name: bili.title, exact: true }).waitFor({ state: 'visible' })
    await page.getByRole('button', { name: '字幕原文', exact: true }).click()
    await page.getByText('1–100 / 237 段', { exact: true }).waitFor({ state: 'visible' })
    await page.locator('.learning-layout').evaluate(element => element.scrollTo({ top: 0 }))
    await page.screenshot({ path: path.join(folder, 'real-bilibili-transcript.png'), fullPage: true })
    for (const item of results.filter(item => item.status === 'failed')) {
      await page.locator('.history-select').filter({ hasText: item.title }).first().click()
      await page.getByText(item.error_message, { exact: true }).waitFor({ state: 'visible' })
      assert.equal(await page.getByRole('button', { name: '生成总结', exact: true }).isDisabled(), true)
      assert.equal(await page.getByRole('button', { name: '下载视频', exact: true }).isEnabled(), true)
    }
    console.log(JSON.stringify({ simulation: false, youtubeCues: ready.cue_count, bilibiliCues: bili.cue_count, captionPagination: true, restore: true, blockedVideosCannotCallAI: true }))
  } finally { await browser.close() }
})().catch(error => { console.error(error.message); process.exitCode = 1 })
